# Fetching the latest node image on apline linux
FROM node:alpine AS builder

# Declaring env
ENV NODE_ENV production

# Setting up the work directory
WORKDIR /frontend

# Installing dependencies
COPY ./package*.json ./
RUN npm install

# Copying all the files in our project
COPY . .

# Building our application
RUN npm run build
CMD ["npm","start"]

