# Fetching the latest node image on apline linux
FROM node:alpine AS builder

# Declaring env
ENV NODE_ENV development

# Setting up the work directory
WORKDIR /backend

# Installing dependencies
COPY ./package*.json ./
RUN npm install

# Copying all the files in our project
COPY . .

EXPOSE 8080
CMD ["npm", "start"]